name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: export RELEASE_VERSION=${{ steps.get_version.outputs.VERSION }} && pnpm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Token
        run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > ./dist/.npmrc

      - name: Publish
        run: pnpm publish ./dist --no-git-checks
